{{- if .Values.frontend.enabled -}}
{{ $name := .Values.Name}}
{{- $name := printf "%s-frontend" $name -}}

apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}

spec:
  selector:
    app: {{ $name }}
  ports:
    - name: http
      port: {{ .Values.frontend.containerPort }}
      targetPort: http

{{- end -}}